<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc11e64f1e4b941d08740230a484831cc
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc11e64f1e4b941d08740230a484831cc::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc11e64f1e4b941d08740230a484831cc::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
